### ISSUE TITLE
RFC - Query Policies

### ISSUE THREAD

**Issue by markstory** [cakephp/authorization#10]
When generating list views, or getting a list of resources, it is simpler and more efficient to bake authorization restrictions into the generated query.

Unfortunately, our existing paradigm of `can() : bool` does not match well to mutating queries as there would be an implicit side-effects with a useless return.

To make the side-effect and intent more specific I think we should expand the `IdentityInterface` and `AuthorizationServiceInterface` to have a new method that allows for queries to have authorization rules applied to them. 

```php
// From an IdentityDecorator instance.
$query = $user->authorizeQuery($this->Articles->find(), 'index')

// From the AuthorizationComponent
$query = $this->Authorization->authorizeQuery($this->Articles->find(), 'index')
```

This API would result in a policy being located for `$query->respository()`. Once located the policy instance would have its `authorizeIndex` method invoked. In the above scenario `App\Policy\ArticlesPolicy::authorizeIndex($user, $query)` would be invoked, and be required to return an updated query object.

### Prior Art

* In [pundit these are referred to as policy scopes](https://github.com/elabs/pundit#scopes).
* Laravel's [Policy classes](https://laravel.com/docs/5.5/authorization#creating-policies) have no equivalent.

**Comment by robertpustulka** [comment]
Looks good. I have concerns about limiting the API to query objects only. What else can be modified using authorization?

**Comment by markstory** [comment]
> I have concerns about limiting the API to query objects only. What else can be modified using authorization?

Maybe we don't have to limit it to queries specifically then. The authorize and can methods won't ever overlap so we could let them be dynamically typed at the interface level.

**Comment by robertpustulka** [comment]
OK then, we can just have `authorize()` method for mutating any objects and `can()` for checking access to them.

Not sure about the name “authorize”. Any other ideas?

**Comment by markstory** [comment]
What about 'restrict', 'resolve', 'constrain'?

**Comment by robertpustulka** [comment]
Maybe “restrict” or just “scope”.

**Comment by markstory** [comment]
So `scopeQuery()` or `applyScope()` as the method name?

**Comment by robertpustulka** [comment]
To me the latter sounds better and does not suggest this should be used only with ORM queries.

So `applyScope` for service/identifier method and `scopeAction` for policy method?

**Comment by markstory** [comment]
I'm good with those method names. I'll get that implemented in the next couple days.

**Comment by robertpustulka** [comment]
Great!

**Comment by burzum** [comment]
Are we going to make the generic or tied to the ORM?

Couldn't we implement this in a way we could filter arbitrary stuff on any object?

**Comment by robertpustulka** [comment]
Should be possible with a custom provider which implements `scope*` methods.

**Comment by markstory** [comment]
> Are we going to make the generic or tied to the ORM?

Right now you can apply a scope to any object that there is a resolver for. It is not tied to the ORM specifically.

**Comment by markstory** [comment]
Closing as this has been implemented.
