### ISSUE TITLE
check authorization for plugin routes

### ISSUE THREAD

**Issue by waspinator** [cakephp/authorization#100]
How would you check authorization for routes provided by a plugin? For example https://github.com/dereuromark/CakePHP-DatabaseLog/tree/master/docs#backend-view

**Comment by markstory** [comment]
You could put the related controllers/routes inside a middleware that used request information to do the relevant authorization checks. Or use the [request policy middleware](https://book.cakephp.org/authorization/1.1/en/request-authorization-middleware.html)

**Comment by dereuromark** [comment]
@waspinator 
I added Request policy in new v2 (master) of TinyAuth now:
https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/AuthorizationPlugin.md#authorization-plugin-support

So in my acl INI file I just set
```ini
[DatabaseLog.admin/DatabaseLog]
* = developer, admin

[DatabaseLog.admin/Logs]
index,view = developer
* = admin
```

**Comment by dereuromark** [comment]
We can probably close this.
