### ISSUE TITLE
Problems with orm resolver and map resolver (server request) in collection

### ISSUE THREAD

**Issue by alexvanniel** [cakephp/authorization#102]
I am really sorry if this is not the properly place to ask this.

My application handles both "things" that can be identified as entities (they have associated models/tables) and also at least one "thing" that does not have any model associated. This is mainly the portal users logging into the system by default land on.
Since it does not have a model associated, the orm resolver will start complaining that no policy for Cake\ORM\Table is defined. Now, I could ofcourse deicde to skipAuthorization but this is action based and not controller.action based.

I would need to either assign a specific action to the portal landing page to skip authorization which I really don't feel comfortable with.

Now I have been looking at adding the RequestAuthorization middleware and use both the orm resolver and a map resolver for the request in a resolver collection. This however does not seem to work because either the server request policy is not satisfied (in case this is an orm related entity) and I get a forbidden error, or the server request policy is satisfied and the orm resolver starts complaining that it is missing the Cake\ORM\Policy (in case this is the portal).

It seems that when the one resolver returns true, the other resolver is then checked anyway even though authorization has been granted. I had expected that when one resolver is satisfied, it would skip any other resolver in the collection. Am I wrong? Is this expected behavior?

Also, I have been looking at maybe switching from the Authorization plugin to the Acl plugin but I am not sure if I can't achieve the same with the Authorization plugin as would be possible with the Acl plugin.

**Comment by markstory** [comment]
> My application handles both "things" that can be identified as entities (they have associated models/tables) and also at least one "thing" that does not have any model associated. This is mainly the portal users logging into the system by default land on.

Does that 'thing' have a class or object type that it is represented by in the application? Or perhaps several things that could be combined with a container object? If yes, then you could use the `MapResolver` to configure a policy for that thing.

> It seems that when the one resolver returns true, the other resolver is then checked anyway even though authorization has been granted. I had expected that when one resolver is satisfied, it would skip any other resolver in the collection. Am I wrong? Is this expected behavior?

Does this happen when using both the requestauthorization middleware and the standard authorization middleware?

> Also, I have been looking at maybe switching from the Authorization plugin to the Acl plugin but I am not sure if I can't achieve the same with the Authorization plugin as would be possible with the Acl plugin.

The AclPlugin is not well maintained at this point. The authorization plugin is where we've been spending effort recently as it allows us to model authorization in ways that are more nuanced than just controller action based.

**Comment by alexvanniel** [comment]
> > My application handles both "things" that can be identified as entities (they have associated models/tables) and also at least one "thing" that does not have any model associated. This is mainly the portal users logging into the system by default land on.
> 
> Does that 'thing' have a class or object type that it is represented by in the application? Or perhaps several things that could be combined with a container object? If yes, then you could use the `MapResolver` to configure a policy for that thing.
> 

The portal/landing page is mainly represented by a controller but nothing more. This might be then something I would need to take advantage of? In other words, try and build a map resolver for it and apply a policy on it?

> > It seems that when the one resolver returns true, the other resolver is then checked anyway even though authorization has been granted. I had expected that when one resolver is satisfied, it would skip any other resolver in the collection. Am I wrong? Is this expected behavior?
> 
> Does this happen when using both the requestauthorization middleware and the standard authorization middleware?
> 

It does indeed. Perhaps it is not supposed to be used together? I was not sure if that was a prudent thing to begin with but documentation is scarce for this particular case.

> > Also, I have been looking at maybe switching from the Authorization plugin to the Acl plugin but I am not sure if I can't achieve the same with the Authorization plugin as would be possible with the Acl plugin.
> 
> The AclPlugin is not well maintained at this point. The authorization plugin is where we've been spending effort recently as it allows us to model authorization in ways that are more nuanced than just controller action based.

That is a bit of a bummer because I have been able to get the Acl plugin to work, or at least installed and created several roles and applied several rules but I was running into the problem of where, how and when to have the Acl plugin check the rules. I was feverishly trying to get it into the User object somehow without making it dirty and thus trying to avoid loading a component, designed for use in a controller, into a model.

Basically what it comes down to is I am trying to find a way to be able to grant or deny a set of permissions based on the membership of a user. I did not see a way for this to happen using Policies. But if you have a great idea, or at least pointers as to how I could achieve something like that with the Authorization plugin, I would love to hear about it. A set of permissions would be role based but needs to be possible to be checked inside a view so to either enable, disable or even hide data, a button, or entire pieces of html. Now I see that $identity can be fetched from the request from inside the view and perform a ->can() check (when using the Authorization plugin). Something I have not figured out how to implement with the Acl plugin, so the Authorization plugin would seem to be more suitable for that. However, the Acl plugin does already equip the role and rule based features I was looking for. I don't know, I guess I really could use an extra pair of brains?

**Comment by markstory** [comment]
> The portal/landing page is mainly represented by a controller but nothing more. This might be then something I would need to take advantage of? In other words, try and build a map resolver for it and apply a policy on it?

Does every logged in user have access to the same controller endpoint? If so then you might not have any authorization to be applied.

> It does indeed. Perhaps it is not supposed to be used together? I was not sure if that was a prudent thing to begin with but documentation is scarce for this particular case.

Yes, I wouldn't use the two together. It isn't clear in the docs but I'll try to improve that. They are intended as two different ways to do authorization as folks on the CakePHP team had uses cases where checking only the controller/action was necessary and others where finer grained resource permissions are a better fit.

> ... I am trying to find a way to be able to grant or deny a set of permissions based on the membership of a user. I did not see a way for this to happen using Policies. But if you have a great idea, or at least pointers as to how I could achieve something like that with the Authorization plugin, I would love to hear about it. 

Inside policies you can use attributes of the identity like their group or role to build your permissions. For example, if you had an content management system where users could only edit their own content unless they were 'site-admins':

```php
class ArticlePolicy
{
  public function canEdit($identity, $article)
  {
    // User is the author.
    if ($identity->id == $article->author_id) {
      return true;
    }
    // site admins can edit anything.
    if ($identity->role == 'site-admin') {
      return true;
    }
    // deny by default.
    return false;
  }
}
```

You would need to define permisisons for each resource you have in your application. If you have a lot of repetitive logic consider using base classes, traits or refactoring common logic into helper objects that your policies use.

**Comment by alexvanniel** [comment]
> 
> 
> > The portal/landing page is mainly represented by a controller but nothing more. This might be then something I would need to take advantage of? In other words, try and build a map resolver for it and apply a policy on it?
> 
> Does every logged in user have access to the same controller endpoint? If so then you might not have any authorization to be applied.
> 
That was exactly what I was thinking too. However, I can't apply the skipAuthorization in the component configuration here because then i would have to add index to the skip and that would mean that *all* indexes would be skipped. That is not what i desire. If I could either add a controller to the skip authorization configuration or maybe do a skipauthorization in-place, that could work. I am not sure if either is supported though.

> > It does indeed. Perhaps it is not supposed to be used together? I was not sure if that was a prudent thing to begin with but documentation is scarce for this particular case.
> 
> Yes, I wouldn't use the two together. It isn't clear in the docs but I'll try to improve that. They are intended as two different ways to do authorization as folks on the CakePHP team had uses cases where checking only the controller/action was necessary and others where finer grained resource permissions are a better fit.
> 
Understood. Thanks.

> You would need to define permisisons for each resource you have in your application. If you have a lot of repetitive logic consider using base classes, traits or refactoring common logic into helper objects that your policies use.

This could work, although I'd rather not resort to hard coding group slugs, names or id's ... Although, the only one redefining the permissions will be me, the developer, and not the administrators... so this might actually work for my particular project.

I'll have a good and hard look at it monday. I'll also start removing the Acl plugin from the project since the Authorization plugin was always the thing I wanted to aim for as it complements the Authentication plugin nicely and it is the official CakePHP of doing things...

**Comment by markstory** [comment]
> That is not what i desire. If I could either add a controller to the skip authorization configuration or maybe do a skipauthorization in-place, that could work. I am not sure if either is supported though.

You can [skip authorization inside of an action](https://book.cakephp.org/authorization/1.1/en/component.html#skipping-authorization)

> This could work, although I'd rather not resort to hard coding group slugs, names or id's ... 

Hard-coding makes for convenient examples. You policies could do additional database queries to a permissions database if that's is how your application needs to handle permissions.

**Comment by alexvanniel** [comment]
> You can [skip authorization inside of an action](https://book.cakephp.org/authorization/1.1/en/component.html#skipping-authorization)

Wow, that was exactly what I was looking for! How did I miss that? Is this in the docs somewhere?
Anyway, this will be sufficient for the modelless controller.

> 
> > This could work, although I'd rather not resort to hard coding group slugs, names or id's ...
> 
> Hard-coding makes for convenient examples. You policies could do additional database queries to a permissions database if that's is how your application needs to handle permissions.

I might consider doing that eventually, but I think hardcoded permissions might be enough for this project.

Thanks a lot for your help! Come monday I will see if I can get it all together.

**Comment by alexvanniel** [comment]
I think I have the bare basics down... so I am now moving from basic to advanced authorization usage *shock horror* Anyway, thank you for your answers and help.
