### ISSUE TITLE
Routing problems in authorization plugin

### ISSUE THREAD

**Issue by bitproITSolutions** [cakephp/authorization#104]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.x-dev
* Authorization plugin Version: 2.x-dev
* Platform and Target: XAMPP, URL of Cake installation http://localhost/subdir/

### What you did
Integrating authorization plugin. I did the setup/config according to the book and attached the plugin to the middleware trying to get things going. 

### What happened
The "unauthorizedHandler" config in AuthorizationService set to "/users/login" redirects to "http://localhost/users/login" ignoring the subdir.

### What you expected to happen
Routing in the authorization plugin should recognize the subdir where Cake is installed.

**Comment by smarek** [comment]
Yes, I can confirm this bug, also the authentication result is funny

```
// current browser url is http://1.2.3.4/subdir/config/login
// dump($this->Authentication->getResult());
Result {#53 ▼
  #_status: "FAILURE_OTHER"
  #_data: null
  #_errors: array:1 [▼
    0 => "Login URL `http://1.2.3.4/config/login` did not match `http://1.2.3.4/config/login`."
  ]
}
```

**Comment by markstory** [comment]
I think #116 should fix this.
