### ISSUE TITLE
Cake4: 500 error after adding AuthorizationServiceProviderInterface

### ISSUE THREAD

**Issue by om1** [cakephp/authorization#111]
I just implemented a fresh cake4 instance and tried to add the Authentification and Authorization plugin interfaces (branch 2.x).  Authentification seems to work as expected. After adding the AuthorizationServiceProviderInterface to the Application class, the application breaks with statuscode 500.  Any suggestion on that?

**Comment by markstory** [comment]
Is there any other information you can provide? Right now we don't have anything that would help us reproduce your issue.

**Comment by om1** [comment]
Here is the code of my Application.php. It breaks after adding AuthorizationServiceProviderInterface.
[https://paste.ofcode.org/dzqKzNXDpWkvhQkgrMYzh9](Application.php)

**Comment by markstory** [comment]
You are missing the ethod required by th authorization provider interface. If you enable debug on your application you should see an error page that gives you a more helpful message and stack trace.

**Comment by om1** [comment]
My debug mode is enabled and no error messages are shown.

**Comment by markstory** [comment]
And that method is commented out in the paste you provided. If debug is on are you not seeing a development error page with the exception message?

Right now the code you have provided will be considered invalid by php as you have the authorizationproviderinterface in your implements list but the method required by that interface doesn't exist.

**Comment by om1** [comment]
Yes i commented it out for testing purpose. No changes after removing the comments. And also there are no error messages. Just a blank page with statuscode 500.

**Comment by markstory** [comment]
It sounds like you haven't implemented the interface correctly then.

**Comment by om1** [comment]
Yes i was thinking the same but where to search for. There isn't mutch to do wrong. Also no error messages ...  Anyway thanks. I try to reinstall the plugin.

**Comment by ndm2** [comment]
You haven't imported `AuthorizationServiceInterface`. That's a fatal error, look in your PHP/server logs if if displaying errors is disabled.

**Comment by om1** [comment]
Yes thats it! Thanks. That import is missing in the 2.0 docs. Dind't checked the imports because with 3.8 everything was working.

**Comment by markstory** [comment]
Which documentation were you using? The import is listed in [these docs](https://book.cakephp.org/authorization/2/en/index.html#getting-started).

**Comment by om1** [comment]
Nope its not. Correct me pls but AuthorizationServiceInterface is not imported in these docs. Just searched for it.

These are the only imports:

use Authorization\AuthorizationService;
use Authorization\AuthorizationServiceProviderInterface;
use Authorization\Middleware\AuthorizationMiddleware;
use Authorization\Policy\OrmResolver;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

**Comment by markstory** [comment]
My mistake. I'll get that updated.
