### ISSUE TITLE
Cannot install in versions 3.x

### ISSUE THREAD

**Issue by eduilson** [cakephp/authorization#118]
**Cake version**: 3.8.7
**Command**: `composer require cakephp/authorization`
**Output:** `cakephp/authorization 2.0.2 requires cakephp/cakephp ^4.0 -> satisfiable by cakephp/cakephp[4.0.0, 4.0.0-RC1, 4.0.0-RC2, 4.0.0-alpha1, 4.0.0-alpha2, 4.0.0-beta1, 4.0.0-beta2, 4.0.0-beta3, 4.0.0-beta4, 4.0.1, 4.0.2, 4.x-dev] but these conflict with your requirements or minimum-stability.`

**Comment by saeideng** [comment]
easiest way is that add the `cakephp/authorization` to your `composer.json` and run `composer update` 
```php
    "require": {
        "cakephp/authorization": "^1.0",
```

version 1.x is compatible with cake 3.x 
and 2.x is compatible with cake 4.x

**Comment by saeideng** [comment]
or do like 
```php
composer require cakephp/authorization "^1.0"
```
