### ISSUE TITLE
skipAuthorization doesn't work when using RequestPolicy

### ISSUE THREAD

**Issue by anuix** [cakephp/authorization#122]
Hello,

I`m using CakePHP4 and I noticed that $this->Authorization->skipAuthorization(); placed in an action doesn't work when using RequestPolicy. 

I have a simple RequestPolicy that retrieves some access rows from the database based on the user's group. 

Can you help me with this?

Thank you!

**Comment by othercorey** [comment]
`RequestAuthorizationMiddleware` checks when the middleware is processed. It is not processed in the component like other policies.
