### ISSUE TITLE
The request to * did not apply any authorization checks when using PRG pattern.

### ISSUE THREAD

**Issue by davidspeijer** [cakephp/authorization#128]
I'm using the https://github.com/FriendsOfCake/search/ plugin to filter data. 

The Search.Search component will allow your filtering forms to be populated using the data in the query params. It uses the PRG pattern (Post, redirect, get). (https://github.com/FriendsOfCake/search/tree/master/docs)

It appears that this authorization plugin cannot handle this pattern as I get the following error:
`The request to /orders/index did not apply any authorization checks.`

I also described the issue at https://github.com/FriendsOfCake/search/issues/265 however the response over there was that this is an issue with the authorization plugin.

my function in the controller:
```
public function index() {
    $this->paginate = [
        'contain' => [
            'Companies',
            'ShippingBarcodes' => ['sort' => ['ShippingBarcodes.id' => 'DESC']]
        ],
        'order' => ['Orders.id' => 'DESC']
    ];
    
    $orders = $this->Orders->find('search', ['search' => $this->request->getQueryParams()]);
    $this->Authorization->authorize($orders);
    $orders = $this->paginate($orders);

    $companies = $this->Orders->Companies->find('list')->where(['Companies.published' => true])->order(['Companies.name' => 'ASC']);
    $statuses = Order::status();

    $this->set(compact('orders','companies','statuses'));
}
```

This is loading the page as expected. The problems occurs once I try to filter the results. The POST results in a status 500: 

> The request to/orders/index did not apply any authorization checks.

Adding a skipAuth is not solving the problem:
```
public function index() {
    $this->Authorization->skipAuthorization();

    $this->paginate = [
        'contain' => [
            'Companies',
            'ShippingBarcodes' => ['sort' => ['ShippingBarcodes.id' => 'DESC']]
        ],
        'order' => ['Orders.id' => 'DESC']
    ];
    .........
}
```
As suggested in https://github.com/FriendsOfCake/search/issues/258 I tried to catch the problem in beforeFilter();
```
public function beforeFilter(\Cake\Event\EventInterface $event)
{
    parent::beforeFilter($event);
    if ($this->request->getParam('action') == 'index' && $this->Authentication->getIdentity()->get('role') == 'admin') {
        $this->Authorization->skipAuthorization();
    }
}
```

This is "solving" the issue as a workaround.

However not as I expect it to work. As I assume that the `$this->Authorization->skipAuthorization()` or `$this->Authorization->authorize($orders)` in the index method should have applied the auth check even with the redirect?

I'm open to any suggestions.

**Comment by markstory** [comment]
The Search plugin does a redirect in its startup method here https://github.com/FriendsOfCake/search/blob/cc1c500a80f1a8d6c3bb3ec90cfe33bd2bfb1733/src/Controller/Component/SearchComponent.php#L69-L83

Because this event happens before your controller action and aborts the request, the skipAuthorization() and authorize() calls in your controller actions are never reached on the redirect response.

**Comment by davidspeijer** [comment]
What is the best solution for this? Should this be changed in de search component? Or is this impossible with the PRG pattern? Is there a solution in the authorization plugin?

**Comment by davidspeijer** [comment]
Created a pull request with the redirect logic moved to beforeRender(). The test is working in my project, not sure what the pro's are thinking about it ;-)

https://github.com/FriendsOfCake/search/pull/282

**Comment by dereuromark** [comment]
The search changes are not good.

> skipAuthorization() and authorize() calls in controller actions

That is the problem. You should never call those inside a controller action IMO.
At that point you already went into the action, thus now it is too late.
Instead, you need to do any auth related topics before, that means specifically `beforeFilter` event at the latest.
This effects the whole eco system. So just changing Search is not helpful, as everyone usually agrees on these kind of specs. Other plugins have the same understanding of event-handling.

**Comment by davidspeijer** [comment]
Thanks for also responding here.

Reading the official cakephp docs I think the writing of my code is correct (not saying it is how it should be, but following the docs guidelines):
https://book.cakephp.org/authorization/2/en/component.html#checking-authorization

I'm open for any suggestion/change as long as both authorization/policies (where my complete app is build around) and search are working together.

**Comment by dereuromark** [comment]
You can use them IF your code so far has "free" access to these actions.
You cannot just have index pages behave differently here IMO if you want the pagination to work filtered as the PRG part of Search component does.
You need to move this part then into a component and load that in your controller for the actions you want to have.

**Comment by davidspeijer** [comment]
@markstory what is your thought on this one?

Am I using the authorization part in the wrong way? Is it possible to load the Authorization earlier?

**Comment by dereuromark** [comment]
https://book.cakephp.org/authorization/2/en/component.html#skipping-authorization
This is definitely wrong in my book - but at the very least quite dangerous to have in there as official docs. 
While you may be able to technically do that, it really goes against the events that are supposed to handle this prior to action access.
Maybe we should clarify that more in the docs, especially if you plan on keeping it agnostic towards eco system Plugins and alike.

**Comment by markstory** [comment]
> That is the problem. You should never call those inside a controller action IMO.

I have to disagree. Authorization checks should be applied to resources or entities, and there is no way to do that generically in the `beforeFilter`. Doing authorization checks in a beforeFilter requires duplicating logic, and making `beforeFilter` aware of the particulars of each action.

If you need to use PRG, you can disable the exceptions/warnings about missing authorization. They are only intended as a development aid and because the missing permission check runs *after* the action is complete it is not a safeguard that prevents bad actors.

**Comment by dereuromark** [comment]
True. Those can be disabled for these actions as well :)

**Comment by davidspeijer** [comment]
Can you guys point me in the right direction on how to do this?

**Comment by markstory** [comment]
You can disable authorization checks in the middleware. An [example is here](https://book.cakephp.org/authorization/2/en/middleware.html#ensuring-authorization-is-applied).

**Comment by davidspeijer** [comment]
> If you need to use PRG, you can disable the exceptions/warnings about missing authorization. They are only intended as a development aid and because the missing permission check runs _after_ the action is complete it is not a safeguard that prevents bad actors.

This is also working. App is working as expected now. Thanks.
