### ISSUE TITLE
Is it possible to create general policy for ORM resolver?

### ISSUE THREAD

**Issue by ulziibadrakh-p** [cakephp/authorization#133]
Can create one general policy instead every entity?
for example create GeneralOrmPolicy instead ArticlePolicy, CommentPolicy.

ArticlePolicy, CommentPolicy have almost same policy logic.

**Comment by markstory** [comment]
The ORM resolver doesn't currently support a fallback/default policy. Would you be using a fallback to define default permissions or just trying to avoid having to define policy methods?

**Comment by infokani** [comment]
I am trying to make authorization that logged in user can access Index, View, Add actions and check owner on Edit, Delete actions for all controller. 
May be this is solution but I don't understand clearly.([User class as identity](https://book.cakephp.org/authorization/2/en/middleware.html#using-your-user-class-as-the-identity))

**Comment by markstory** [comment]
The user class as identity would be helpful, but more is needed. Right now you would need to use the chain resolver and build a resolver class that always returns your GeneralPolicy class. Then you could put the OrmResolver first in the chain, and your generic resolver second. Doing this would let you to add specific policies for models as you need them.

**Comment by othercorey** [comment]
Closing this as the solution is a custom resolver.
