### ISSUE TITLE
Can I use can[Action] in a view?

### ISSUE THREAD

**Issue by rickcc** [cakephp/authorization#134]
I would like to check authorization actions such as canEdit, canCreate etc. in a cake view so that I can display or omit related links to other views/actions appropriately. At present I use authorization in the controller successfully with each of the canAction checks in the controller actions, but the user experience then means they click a link and receive an authorization failure. 

I’d prefer to only show relevant links as well. Not to substitute for the checks in the controller (smart users could type commands into url bar or use curl to circumvent) but to supplement them for a better front end experience. 

There is a simple view helper for authentication, do we need one for authorization too or is there an elegant solution I’ve missed?

**Comment by markstory** [comment]
> There is a simple view helper for authentication, do we need one for authorization too or is there an elegant solution I’ve missed?

Yes, you can access the `identity` request attribute in templates and use its methods to check authorization. For example:

```php
$user = $this->request->getAttribute('identity');
if ($user->can('update', $article) {
  echo $this->Html->link(...);
}
```

If you need to check authorization often in the views you can use a `beforeRender` callback to set the user into the view variables all the time.

**Comment by rickcc** [comment]
Thanks - perfect!
