### ISSUE TITLE
Custom bake Policy template

### ISSUE THREAD

**Issue by blieb** [cakephp/authorization#138]
Hi,

Is is posible to create a custom bake template for the policy?

I've created `/src/Template/Bake/policy.twig` (cakephp 3.x) But this file is not used when I run the bake command. I need to change some little things in template for my project. Else I have to edit it every time when I make a new Policy.

**Comment by markstory** [comment]
I think your file will need to be `Template/Authorization/Bake/policy.twig` but I could be wrong, it has been a while since I looked at how template paths are resolved for bake in 3.x

**Comment by blieb** [comment]
> I think your file will need to be `Template/Authorization/Bake/policy.twig` but I could be wrong, it has been a while since I looked at how template paths are resolved for bake in 3.x

Yes tried that do, was already playing with the directories on information with what I saw, but unable to get it work yet. Trying to figure out now template paths are resolved.

**Comment by othercorey** [comment]
I think it would be `Template/Plugin/Authorization/Bake/policy.twig`

**Comment by blieb** [comment]
> I think it would be `Template/Plugin/Authorization/Bake/policy.twig`

Ah tnx! that works! did not try to add 'Plugin' in path 👍
