### ISSUE TITLE
Redirect is not working for me

### ISSUE THREAD

**Issue by enviniom** [cakephp/authorization#141]
Hi, I can't make a redirect for unathorized actions, and i made configuration like say in docs:

``` 
'unauthorizedHandler' => [
                    'className' => 'Authorization.Redirect',
                    'url' => '/principal/noauthorized',
                    'queryParam' => 'redirectUrl',
                    'exceptions' => [
                        MissingIdentityException::class,
                        OtherException::class,
                    ],
                ], 
```
But, still shows the error page with "Identity is not authorized to perform (...)" and I can't redirect to /principal/noauthorized

**Comment by ndm2** [comment]
You'd have to add `\Authorization\Exception\ForbiddenException` to the list of handled `exceptions` to catch those errors, that is what is being thrown by the request handler middleware and by the authorization component (unless you're doing manual `can*` checks).

https://stackoverflow.com/questions/59976845/cakephp-4-authentication-plugin-requestauthorizationmiddleware-redirect-url-miss/59977415#59977415

**Comment by enviniom** [comment]
Thanks a lot, now it is working.
