### ISSUE TITLE
Can't use i18n and get plugin in different locale

### ISSUE THREAD

**Issue by mcube27** [cakephp/authorization#143]
After using the plugin in a Cakephp 3.8 app, I realized that you cannot use bin\cake i18n extract to get the plugin in your app locale.

It would be nice to be able to use this tool as for cake core.

**Comment by markstory** [comment]
I don't entirely understand what commands you're running and what you're expecting the results to be. Could you provide the commands you were running?

**Comment by mcube27** [comment]
I would like to run `bin/cake i18n extract` on Authorization plugin to translate the thrown exceptions. 

I use cakephp as an api and return the thrown exceptions. It would be nice if they were translated.

**Comment by garas** [comment]
Which exception messages you think should be translatable?

Most exceptions are helpers for developers about invalid app code (invalid data types, classes, configuration) and are not intended to be displayed to end user.

**Comment by mcube27** [comment]
I understand that exception are a way to help developers but my request is mainly for this exception message :
https://github.com/cakephp/authorization/blob/3e9a171082855b6bae4c12cc88f63514b9645102/src/Exception/ForbiddenException.php#L32
I know that there is the `Exception::result` that can be used, but it means adapting the exception renderer on the client side of the api, which is not ideal.
