### ISSUE TITLE
Do we want to provide routes / route scope auth out of the box?

### ISSUE THREAD

**Issue by burzum** [cakephp/authorization#16]
Do we want to allow people to authorize against a resolved route or route scopes?

If yes, any ideas on how to do it the best? Through a middleware? 

Common use case: `/admin` or other prefixes for areas that only an identity with a specific role is allowed to access.

**Comment by markstory** [comment]
What would the 'resource' be in the route scope scenario? How would you see these scoped routes being configured.

**Comment by robertpustulka** [comment]
This could be achieved by creating a policy for `ServerRequest` and authorizing the request through a custom middleware.

**Comment by robertpustulka** [comment]
Does #39 implement a feature requested here? @burzum

**Comment by burzum** [comment]
@robertpustulka yes

**Comment by robertpustulka** [comment]
OK, I'm closing this.
