### ISSUE TITLE
MissingPolicyException using Paginator 

### ISSUE THREAD

**Issue by gludie** [cakephp/authorization#160]
I tend to use already existing policies to show / hide links, elements, ... in my templates.
Works like expected (setup fine and have various policies in place), but suddenly when paginator comes into the game I get a MissingPolicyException _"Policy for Cake\ORM\ResultSet has not been defined"_ after paginating a resultset. Seems, that the repository can not be resolved after pagination ? 

Option 1 (not nice): provide manually the Tablemodel (eg. $user->canResult('export', new AnimalTable());
Option 2 (may be even better and not a workaround): determine acl for elements in view or controller to be displayed on specific template

Example: 
Controller:
$query =$this->TheTable->find(); 
$paginated = $this->paginate($query);

$query2 = $this->TheTable->find();
... set ...

View/Template:
if ($user->can('export', $paginated)) ... MissingPolicyException
if ($user->can('export', $query2)) ... right policy resolved

Would you see it as an issue of the authorization / paginator or probably a design/wrong approach issue ?

**Comment by markstory** [comment]
You can't apply the policy on the result set as it is  no longer a query, so the scope methods won't really work as documented.

Instead you could apply authorization to the query before pagination, or to individual records as they are read from the result set.

**Comment by gludie** [comment]
thanks, I see ..., I was in the believe, that there might be some places I overlooked, cause acc. API doc the resultset constructor saves the repository of the query in  _defaultTable (protected) 

I shortly did a quick dirty check using above example:
providing an accessor in ResultSet.php:
    public function getDefaultTable() { return $this->_defaultTable; }

after pagination: 
if ($user->can('export', $paginated->getDefaultTable())) ... right policy resolved

so the resultset have the repository of the query, but may be there is a good reason, why there is not a getter for it.
 
anyhow, i believe I will reconsider my design approach but would be interested in your opinion.

**Comment by gludie** [comment]
one more thing: this could also help, but then the entity policy is of course resolved ...
$user->can('export', $paginated->first() )

but ...

**Comment by gludie** [comment]
going via specific entities or records brings also other necessary checks ...  
 if ( ($paginated->first() !== null) && $user->can('export', $paginated->first() ) ) : ?>

well, I guess, I can close it now for the time being, thx for the fast reply.

**Comment by markstory** [comment]
The resultset does contain the repository, but there is no `getDefaultTable()` method. The lack of a public method to get the repository out is one reason that policies can't be resolved from ResultSet objects. Another reason policies can't be resolved from ResultSets is that I don't understand the use case around it.

Beyond doing a role/userid check I don't understand what a policy would do with a ResultSet. Would it be looking at each of the rows? If that is desired a scope should be applied to the query *before* it is converted to a ResultSet so that unauthorized rows are not loaded. If the desired check is to see if a user can 'export comments' then couldn't the table object be passed to the view to do this check?

**Comment by gludie** [comment]
totally with you , see it the same and and it is about use case 2 - based on model and role some elements should be disabled or not shown at all ... for sure there comes also a RequestPolicy into the game at some places ... the approach to just pass another (table) object to the view to resolve the right policy didnt come into my mind, was too much ‚focused‘ on the very simple query object (correct: resultset ;-)) Ihad already in my view available ... shortcoming or a concern I  see, that objects will be instantiated only for the resolver ? (resources) ... beside the fact, that there is also the opportunity to create my own policyresolver : what s about giving just the policyname I want to use for the policycheck?

**Comment by markstory** [comment]
What would the method look like when an explicit policy class was used?
