### ISSUE TITLE
Check entity authorization inside entity

### ISSUE THREAD

**Issue by blieb** [cakephp/authorization#168]
Hi,

I'm currently working on a api, I respond all entities that user can see. But user can see more than he can edit. So I need to add to the response if the logged in user can edit the entity.

what is the best method to add this? I was thinking making a virtual field inside entity that shows if user can edit. But I can't access the authorisation plugin or user entity from there. Any other ways to do this?

**Comment by markstory** [comment]
> what is the best method to add this? I was thinking making a virtual field inside entity that shows if user can edit. But I can't access the authorisation plugin or user entity from there. Any other ways to do this?

I would do this when you're converting the entities to JSON. If your application is just serializing entities right now you might need to wrap those entities or process them before passing them to the view.

A package like [this one](https://github.com/andrej-griniuk/cakephp-fractal-transformer-view) might be something you could explore. Having the API serialization separate from the entity would let you add in permissions meta data and things like hypermedia links if you need those too.

**Comment by blieb** [comment]
> > what is the best method to add this? I was thinking making a virtual field inside entity that shows if user can edit. But I can't access the authorisation plugin or user entity from there. Any other ways to do this?
> 
> I would do this when you're converting the entities to JSON. If your application is just serializing entities right now you might need to wrap those entities or process them before passing them to the view.
> 
> A package like [this one](https://github.com/andrej-griniuk/cakephp-fractal-transformer-view) might be something you could explore. Having the API serialization separate from the entity would let you add in permissions meta data and things like hypermedia links if you need those too.

Tnx for the tip, I wanted to do in inside the entity, but since I use the CRUD plugin I created a listener that adds it to the response.
