### ISSUE TITLE
RFC: Make `access` the action verb for authorization

### ISSUE THREAD

**Issue by othercorey** [cakephp/authorization#172]
Naming
---

Authorization currently uses `authorize` to describe checking permissions and rejecting the user if permissions fail. However, in physical security, `authorize` refers to a configuration change which sets the permissions of a user for an action. You would not `authorize` when entering a room.

Users would typically try to `access` a resource either physically or virtually. Accessing a room would check the users permissions and either allow them to enter or reject them and remain closed.

We want to use a word that makes sense for both the security check and the action taken after permissions pass or fail. When permissions fail with `authorize()`, an exception is thrown. Other alternatives such as `check` make sense when evaluating permissions, but you would not expect an exception to be thrown.

Future use of the term `access()` such as `checkAccess()` and `canAccess()` are also consistent and clear.

API Changes
---

* `AuthorizationComponent::authorize()` => `AuthorizationComponent::access()`
* `AuthorizationComponent::authorizeModel()` => `AuthorizationComponent::setConfig()`
* `AuthorizationComponent::mapAction()` => `AuthorizationComponent::setConfig()`

AuthorizationComponent::access()
---

`access($resource, ?string $action= null): void`

~Along with the function name change, the second parameter `$action` would be renamed to `$scope` to avoid confusion with Controller actions. Although the default `scope` is the name of the Controller `action`, they can mean two different things.~

~We already use the term `scope` in Authorization to mean the type of access requested for a resource. It make sense to use it consistently.~

AuthorizationComponent::setConfig()
---

Some of the helper functions were re-using the terms `authorize` with a different meaning. They were setting a configuration used by later calls to `authorize()` instead of actually performing the access check. This is confusing for the user.

As these calls are just setting a configuration, we should create a simple `action => config` mapping in the component config that user can set to control all of these features.

```php
'action' => [
  'skip' => true,
  'model' => true,
]

$component->setConfig('action.skip', true);
$component->setConfig('action.scope', 'index');
```

This also removes the confusion `mapAction()` function which is also difficult to rename and just sets a config value. Users would have to follow the implementation to understand which type of action is referenced.

**Comment by othercorey** [comment]
I should point out that I'm suggesting a config format change to combine the various action-specific configs into a single `action => [config]` format. This will avoid the need for confusing functions.

**Comment by ADmad** [comment]
:+1: for `AuthorizationComponent::authorize()` => `AuthorizationComponent::access()`, short sure about replacing the other methods with `setConfig()`. I haven't used the component enough to have an informed opinion on it.

**Comment by othercorey** [comment]
> 👍 for `AuthorizationComponent::authorize()` => `AuthorizationComponent::access()`, not sure about replacing the other methods with `setConfig()`. I haven't used the component enough to have an informed opinion on it.

The reason for the change is `authorizeModel()` doesn't make sense especially now. I could replace it with another name, but seemed awkward.

It's an alternative for discussion.

**Comment by markstory** [comment]
> We already use the term scope in Authorization to mean the type of access requested for a resource. It make sense to use it consistently.

Using `scope` to mean two different things in this plugin is a bit concerning to me. Could `access()` use operation instead?

**Comment by othercorey** [comment]
> Using `scope` to mean two different things in this plugin is a bit concerning to me. Could `access()` use operation instead?

I also want a consistent word for the "type of access" being requested for anything. It's currently "action", and I think that's confusing. I was going to suggest `scope` since we have `applyScope` ... but maybe that name needs to be adjusted as well since `apply` doesn't make sense.

**Comment by markstory** [comment]
The idea behind apply was that those methods mutate a query or selection so that access controls have been 'applied'.

**Comment by othercorey** [comment]
The concept of apply scope make sense. I'm not sure if we can make `scope`, `action`, `operation` consistent in all places.
