### ISSUE TITLE
Deprecated logs after update to CakePHP 4.3 and PHP 8.1.0

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/authorization#191]
After update my CakePHP to 4.3.2 and PHP to 8.1.0 some Deprecated warning occurred on class IdentityDecorator.

My question is, is this a problem in my code or in the plugin?

The stack:
Deprecated (8192): Return type of Authorization\IdentityDecorator::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in [/var/www/Coins/vendor/cakephp/authorization/src/IdentityDecorator.php, line 169]
Request URL: /logs/compact
Referer URL: https://coins-sandbox.wss.group/logs
Client IP: 162.158.62.118
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 185
include - /var/www/Coins/vendor/cakephp/authorization/src/Identity.php, line 25
Composer\Autoload\includeFile - /var/www/Coins/vendor/composer/ClassLoader.php, line 571
Composer\Autoload\ClassLoader::loadClass() - /var/www/Coins/vendor/composer/ClassLoader.php, line 428
Authorization\Middleware\AuthorizationMiddleware::buildIdentity() - /var/www/Coins/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php, line 207
Authorization\Middleware\AuthorizationMiddleware::process() - /var/www/Coins/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php, line 124
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Authentication\Middleware\AuthenticationMiddleware::process() - /var/www/Coins/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php, line 124
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Middleware\EncryptedCookieMiddleware::process() - CORE/src/Http/Middleware/EncryptedCookieMiddleware.php, line 93
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Middleware\CsrfProtectionMiddleware::process() - CORE/src/Http/Middleware/CsrfProtectionMiddleware.php, line 174
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Middleware\BodyParserMiddleware::process() - CORE/src/Http/Middleware/BodyParserMiddleware.php, line 157
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Routing\Middleware\RoutingMiddleware::process() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 161
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Routing\Middleware\AssetMiddleware::process() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 68
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Error\Middleware\ErrorHandlerMiddleware::process() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 126
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 58
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 90
[main] - ROOT/webroot/index.php, line 40

**Comment by markstory** [comment]
> My question is, is this a problem in my code or in the plugin?

These are deprecations that are related to the Authorization plugin.

**Comment by markstory** [comment]
Looks like this has been fixed on 2.x and just needs to be released.
