### ISSUE TITLE
[RFC] Support plugin map in OrmResolver

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/authorization#21]
I have a use case, where I have my app logic in a plugin (let's cal it a logic plugin) and use there some models from another plugin (call it data plugin).

Currently the only way to define policies for my models is to:
- add policies to the "data plugin" (not possible in my case)
- add policies to my app (breaks my design, where logic is defined in a logic plugin)
- use map resolver and map each "data plugin" model to the policy in a "logic plugin" (makes little sense)
- extend each "data plugin" model in "logic plugin" model and use those instead (still lots of senseless work)

My idea is to have the ability to map plugins in a resolver so the policies would be looked for in another plugin. For example:
```php
new OrmResolver([
    'appNamespace' => 'MyApp',
    'pluginMap' => [
        'DataPlugin' => 'LogicPlugin'
    ]
]);
```

What is your opinion on this?

**Comment by markstory** [comment]
Seems reasonable to me.

**Comment by robertpustulka** [comment]
Should the policies for DataPlugin be looked for in `LogicPlugin\Policy\DataPlugin` as the app overrides or just in the root namespace?

**Comment by markstory** [comment]
I don't know. But it seems excessive to have overrides in an override.
