### ISSUE TITLE
Feature request: Make Authorization service available via DI in the Middleware

### ISSUE THREAD

**Issue by manuelpeiso** [cakephp/authorization#282]
There was a previous discussions about this: https://github.com/cakephp/authorization/issues/265

This capability was added in the branch 2.next of the authorization plugin but for some reason is not available in 3.x or 3.next. Is there any reason why the authorization service is not available via DI in 3.x?

**Comment by jamisonbryant** [comment]
Thanks for the reminder, I just created #283. Please take a look!

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/authorization/pull/284
please approve.
