### ISSUE TITLE
Can't implement __call() on a policy object.

### ISSUE THREAD

**Issue by burzum** [cakephp/authorization#37]
I'm trying to implement `__call()` in a policy so I can delegate the data to a lookup in a database table.

This doesn't work because `method_exists()` doesn't check for  `__call() .

Can I push this change?

```php
    protected function getCanHandler($policy, $action)
    {
        $method = 'can' . ucfirst($action);

        if (!method_exists($policy, $method) && !method_exists($policy,' __call')) {
            throw new MissingMethodException([$method, $action, get_class($policy)]);
        }

        return [$policy, $method];
    }
```

**Comment by markstory** [comment]
I think that is reasonable. Using `__call` allows more dynamic usage patterns.

**Comment by robertpustulka** [comment]
You can also implement `BeforePolicyInterface` in your policy and make an early check in `before()` hook.
