### ISSUE TITLE
AuthorizationComponent::authorize() should now throw an exception

### ISSUE THREAD

**Issue by burzum** [cakephp/authorization#42]
I think this should return bool instead. The exception should be thrown in authorizeAction() because this is the automated action check and it is likely that I don't want to display it at all. But authorize() should give me the option to decide what I want to do instead of requiring me to wrap the call in a try/catch.

@markstory told me this on Slack before he went offline:

> The middleware lets you configure how unauthorized exceptions are handled. Does it need to be in the component?

If the article is not allowed to be viewed I want to show a flash message and redirect back to from where ever the user came from and not relying on a generic handler, probably redirecting me to a login page. Or what if I would like to stay on the current page but render a paywall like page? I would have to handle the exception again. An exception feels wrong here in any case. It's not an exception but an expected result that I either can or can't access the action.

**Comment by markstory** [comment]
I'm not a fan of introducing a breaking change to the existing method. What do you think about adding another method that returns `bool` instead of a throwing an exception when authorization fails?

**Comment by robertpustulka** [comment]
I think we could add a `can` method to the component for such cases.

```php
if ($this->Authorization->can('edit', $article)) {
    ...
}
```
^ for authorization checks

```php
$this->Authorization->authorize('edit', $article));
```
^ for restricting access using an exception

---

> I'm not a fan of introducing a breaking change to the existing method.

We already did in #40, #41

**Comment by burzum** [comment]
@markstory  this is what we still have in the readme the the version is still beta. I don't see a problem in making breaking changes until we get pass the RC releases?

> This is still under active development and APIs may change without notice ⚠️

I would prefer one method, but OK. I can add `can` or `isAuthorzed`. Which one do you prefer?

**Comment by robertpustulka** [comment]
>  I don't see a problem in making breaking changes until we get pass the RC releases?

I see because I would need to change my code. As I need to do with changes made in #40.

It's nice though that you are discussing those changes in a public issue before posting and merging a PR.

**Comment by burzum** [comment]
@robertpustulka well, it is still a beta and the readme tells you that breaking changes are expected. I really dislike the idea of already adding legacy code and workarounds to something that is clearly considered as "work in progress". We should get it as good and right for all cases as possible until we are past the RC phase. And the change in 40 was discussed with @markstory on Slack before.

**Comment by robertpustulka** [comment]
> And the change in 40 was discussed with @markstory on Slack before.

On slack, but not in public. The discussion and the decision has been made behind the back of the community. And that's not how the OSS work.

> I really dislike the idea of already adding legacy code and workarounds to something that is clearly considered as "work in progress". 

I agree, but IMO the feature discussed in this issue is not a workaround.
I believe that we need both - the ability to quickly check the access without calling the identity directly (`$this->AutAuthorizationhorize->can()`) and the ability to quickly check access and throw an exception (`$this->Authorization->authorize()`).

**Comment by burzum** [comment]
can() and authorize() are very similar but very different named. We should find a better name that reflects their purpose better.

I consider Mark as the authority to make a decision, I'm not a big fan of endless discussions and there was a study that showed that a project with a strong lead is more successfully than others that tend to talk to much. Actually we have plenty of open issues on CakePHP that have a discussion stuck in the middle of something without a result or a final decision. It is also pretty frustrating for the person who created the issue or the PR to wait for weeks without any response.

**Comment by robertpustulka** [comment]
> can() and authorize() are very similar but very different named. We should find a better name that reflects their purpose better.

I think that `authorize` name inflicts that an action is being done (eq "to authorize" - check and pass/hold) while `can` seems like a just a check. To me names reflect the purposes pretty well, but I'm open for ideas. I just want to keep the current behavior (check access and throw an exception immediately).

**Comment by burzum** [comment]
@robertpustulka I don't have a better idea right now. So merge the PR?

**Comment by burzum** [comment]
Closing this in favor of the PR.
