### ISSUE TITLE
Cake 3.6 compatibility

### ISSUE THREAD

**Issue by josbeir** [cakephp/authorization#48]
The line below should be updated to getRepository() but when doing this some tests fail because getRepository() is not implemented in Cake\Datasource\QueryInterface, instead it is available in Cake\Datasource\QueryTrait. I didnt open a PR for this because it should be updated in core first.

https://github.com/cakephp/authorization/blob/9d98931e8baf7fb7abe60a1cf7850fb2a87b1de8/src/Policy/OrmResolver.php#L72

**Comment by markstory** [comment]
We can't change that line as it will break compatibility with applications using 3.5. There was a discussion here https://github.com/cakephp/authorization/pull/45#discussion_r183356715

**Comment by josbeir** [comment]
Ah right, i'll use E_USER_DEPRECATED for the time being :-)
