### ISSUE TITLE
Release incorrect

### ISSUE THREAD

**Issue by josbeir** [cakephp/authorization#52]
As stated on slack:
"pssst @markstory you released a new version of this plugin including the new RequestAuthorizationMiddleware, but somehow it's still an older version of the branch, (12 commits behind) so its missing that middleware :-)"

**Comment by markstory** [comment]
@josbeir My mistake, I'll tag another release and update the release page.

**Comment by markstory** [comment]
Fixed now. 1.0.0-beta7 has been tagged.
