### ISSUE TITLE
Expected that `identity` would be an instance of Authorization\IdentityInterface, but got Authentication\Identity

### ISSUE THREAD

**Issue by hiryu85** [cakephp/authorization#58]
Hello!
I can use cakephp/authentication and cakephp/authorization?

Edit: Maybe is possibile if i change the identity key from Middleware.. I ask if it is normal to receive this exception, and if changing the key is a good approach to solving the problem.

**Comment by markstory** [comment]
>  I can use cakephp/authentication and cakephp/authorization?

Yes they can be used together. Are you creating your own Identity object?

**Comment by hiryu85** [comment]
No @markstory

**Comment by hiryu85** [comment]
I found the possible cause of this problem. In my AppController I loaded the components in order: Authorization, Authentication.
By reversing the order, it works.

**Comment by markstory** [comment]
How could someone reproduce the problem you're having?

**Comment by hiryu85** [comment]
I Will create a repository when return to home. Thank you for help

Il giorno dom 28 ott 2018, 03:11 Mark Story <notifications@github.com> ha
scritto:

**Comment by garas** [comment]
`AuthorizationMiddleware` must be after `AuthenticationMiddleware` in `Application::middleware()`.

As documented in [Quick Start and Introduction to the basics](https://github.com/cakephp/authorization/blob/master/docs/Quick-start-and-introduction.md):

... Then add the following to your `middleware()` method:

```php
// Add authorization (after authentication if you are using that plugin too).
$middleware->add(new AuthorizationMiddleware($this));
```

**Comment by hiryu85** [comment]
I think we can close this issue.. 
Loading AuthenticationMiddleware before AuthorizationMiddleware resolve this defect.

Even if all using Authentication.IdentifyHelper raise another Exception but perhaps it is the case that I tell you about cakephp/authentication repository. 
What do you think @markstory ?

**Comment by ravage84** [comment]
If one fo you guys think we can improve the documentation in some way,, please open an issue or a pull request on the https://github.com/cakephp/docs repo.
