### ISSUE TITLE
MissingIdentityException unused

### ISSUE THREAD

**Issue by jeremyharris** [cakephp/authorization#59]
I traced a difference between the two versions of the plugin I'm using to this commit: https://github.com/cakephp/authorization/commit/e682a4ce309ad28c332708678791a635032a77ea

In it, the MissingIdentityException is no longer thrown (it now throws a ForbiddenException). This prevents an unauthorizedHandler from redirecting to the login page when no one is logged in during an authorization check. All of the documentation mentions catching this exception as examples of using the unauthorizedHandler.

What would be a way to continue supporting the previous MissingIdentityException behavior while still preserving the fix that commit intended?

**Comment by Zuluru** [comment]
My understanding is this was changed to allow the policies to allow access to unauthenticated users. I think you could throw this exception in your policy, using the `before` functionality if you need to do it everywhere?

**Comment by jeremyharris** [comment]
I am already throwing it within my application code, however I wanted to report the change in functionality (albeit between betas).

It sounds like this won't come back so I think I'll open a PR to update the docs as they're misleading/incorrect now. I'll also work up an example to make it easier for users who are migrating from the AuthComponent.

**Comment by Zuluru** [comment]
Please share your posts here too; I don't get onto the slack all that often! I've summarized my use cases and findings in #62; maybe there's some commonality between where we're headed.

**Comment by dereuromark** [comment]
I am also confused on how this should work out now for normal redirect topics.

**Comment by markstory** [comment]
When we updated the code to handle the no-user scenarios without an error the `MissingIdentityException` became mostly unused. This was done in #40 to make authorization missing users possible. Because of those changes `MissingIdentityException` isn't raised as often anymore.

> I think you could throw this exception in your policy, using the before functionality if you need to do it everywhere?

Is correct. I can work on some documentation updates for this.
