### ISSUE TITLE
Component doesn't handle non-object resources

### ISSUE THREAD

**Issue by Zuluru** [cakephp/authorization#60]
In a number of places through the plugin, calls to `get_class($resource)` are preceded by `if (is_object($resource))`. But in `AuthorizationComponent::authorize`, if the action is not authorized, the parameters passed to the `ForbiddenException` constructor don't have this check, they just call `get_class($resource)`. I am building a resolver that just takes a string for the policy class name instead of deducing it from an object, and it fails in these cases because of this. It seems that this is likely just an oversight; I can easily put together a PR to correct it, if it's an actual defect instead of intentional behaviour.

**Comment by markstory** [comment]
> I can easily put together a PR to correct it, if it's an actual defect instead of intentional behaviour.

Supporting resolvers with non-object arguments is something we'd like to do. We have clearly not done a good job of testing that behavior in an integrated way.

**Comment by Zuluru** [comment]
I can submit my string-based resolver for consideration at some point, if you want, but it's not quite ready to see the light of day.

**Comment by markstory** [comment]
> I don't see an obvious way to add a test for the fix without adding an entire string-based resolver class.

That's ok. It could live in the `tests` directory and won't be part of the autoloader for the plugin.

**Comment by markstory** [comment]
Hoping to avoid adding stub class to the tests folder? We already have a bunch of [stub classes](https://github.com/cakephp/authorization/tree/master/tests/test_app/TestApp).

**Comment by dereuromark** [comment]
Resolved with opened PR.
