### ISSUE TITLE
Flash messages and redirect URLs for authorization failures

### ISSUE THREAD

**Issue by Zuluru** [cakephp/authorization#62]
I don't see any way to set the flash message that gets used in case of authorization (or authentication) failures, or provide custom redirect URLs for different policy failures (e.g. redirect to a view when edit isn't allowed). I've tried added this capability in my app by writing my own "unauthorized" handler and throwing custom exceptions from my policies; the handler pulls the required details from these and proceeds accordingly. But while the exceptions work okay for actual authorization checks (`$this->Authorization->authorize()`), they cause problems when doing authorization *tests* (`$this->Authorization->can()`).

I've had to write quite a bit of code to get close to functionality that the old Auth component had, so I feel like I may be missing something. Or maybe the plugins just haven't had it added yet? Happy to work towards a PR if this is the sort of thing that the plugin should support natively.

**Comment by markstory** [comment]
> I don't see any way to set the flash message that gets used in case of authorization (or authentication) failures, or provide custom redirect URLs for different policy failures (e.g. redirect to a view when edit isn't allowed).

This isn't something we've implemented. Custom exceptions is how I would approach this problem as well. What isn't working well with `can()` and custom exceptions? Perhaps we can make that better.

**Comment by Zuluru** [comment]
I have a number of functions that I've built into my test suite, for checking return values (status codes, flash messages, redirect URLs, body content) in various test scenarios. I'm working my way though reducing this list down to the bare minimum of unique authentication and authorization scenarios that I need to deal with. (I suspect that I may be trying overly hard to give helpful messages and redirects to people that try to do things they aren't allowed to do, but between cached search engine results and emailed links that go stale, there are a number of situations where someone *could* have done something, but no longer can, and I want to be user-friendly in such cases, to reduce the number of support emails if nothing else.) Anyway, this winnowing process is taking some time. Hope to have some results from that, and an accompanying analysis of what works and what doesn't soon.

In the meantime, I did come across something (for probably the third time) that is part of this. The authorization component can be given a 'skipAuthorization' list. But all that happens with these functions is that they are not flagged as not having been authorized by the end of the process. If one calls `$this->Authorization->authorize()` in one of those functions, the authorization is still run. I can see arguments both for and against this behaviour; I just wanted to confirm that it is intentional as it stands, not a bug that will be fixed at some point.

**Comment by Zuluru** [comment]
Okay, I've winnowed this down to what I think are my minimum basic usage cases. For some of the examples to make sense, it's perhaps useful to know that this is a sports league management system. Lots of optional features, lots of views that are very much role-reliant, and lots of things that are time-critical.

1. Unauthenticated access to an obsolete public resource (e.g. player profile for a deactivated user, or ical schedule for a team that's done). Respond with HTTP code 410 GONE (mainly in hope that Google, etc. will stop asking for it).

2. Unauthenticated access (e.g. members-only view) resulting in a redirect to the login page, with parameter directing back to the resource after login, and a generic "You must log in" flash message.

3. Unauthenticated access resulting in a redirect to some public page (set by the action, not a single pre-configured URL), for situations where the resource isn't available even with a login (e.g. a disabled feature: if it's requesting stats for a team that doesn't have stats, redirect to the team view page). Needs to handle situations where no flash message is set and where a flash message is set.

The next two are analogs to 2 and 3, except unauthorized instead of unauthenticated.

4. Unauthorized access (e.g. admin-only view) resulting in a redirect to the home page, with a generic "You do not have permission" flash message.

5. Very much the same scenarios and results as 3, except the error comes from the authorization process, not authentication.

Now, as to how these things work. The good news is that, having enumerated all these situations, I was able to pull examples of each into a central controller test, which made it easier to debug the last issues, so it's all working now (modulo the plugin adjustment mentioned in #2 below).

1. Handled by throwing a stock GoneException. This is easy.

2. Between the "unauthenticatedRedirect" and "queryParam" config options on the AuthenticationMiddleware, the redirect portion of this works fine. The startup event handler of the AuthenticationComponent throws an UnauthenticatedException, which the Middleware catches, building a redirect URL that is attached to the response. But there's no capability here for a flash message, which was a core feature of the old Auth component. I see a few possible solutions, but by far the simplest seems to be to allow the component to be configured with an optional message (or, more generically, an optional uauthenticated handler). This causes no breakage of existing code, and restores prior functionality that people are familiar with.

3. Handling these by allowing unauthenticated access, then failing the authorization check per how #5 is handled below. This seems to me like a perfectly viable way to deal with this situation.

4. My custom unauthorized handler intercepts ForbiddenExceptions, injecting the flash message, and redirecting to the home page.

5. My custom unauthorized handler intercepts MissingIdentityExceptions, for things like situation 3 above, adding my default flash message and redirecting to my configured "unauthenticated" URL. It also intercepts a custom exception that I've created (which accepts a message and redirect URL), flashing and redirecting as you'd expect.

This is all working now, and I think this framework will handle all my needs. But to deal with situations 3-5, I have had to create a custom exception, a custom unauthorized handler, and handler functions for each of the three exceptions I need to handle. This feels like a bit of a heavy burden to put on anyone who has diverse authorization needs. To me, these needs don't seem unusual, so raising a barrier like this impedes adoption. I think that my custom handler functionality could be built into the existing RedirectHandler without breaking any existing functionality, but providing extended options. This means that the only custom code people would need to write is their own exception handlers, which we can provide an example of in the documentation.

**Comment by Zuluru** [comment]
This doesn't address my issues with mixing `can` with exceptions. I'm not sure if my other fixes have also resolved this. To be determined in the next couple days...

**Comment by Zuluru** [comment]
I've now run into a few instances again of places where the current setup requires me to catch exceptions thrown by `can`, which still seems counter-intuitive to me. Anyone have thoughts on this, or my suggested change in item 2 above? These are the two highest priority items for me, and I can do PRs for them quickly if the concepts are deemed sound.

**Comment by markstory** [comment]
A potential solution would be to catch and swallow all exceptions inside `can()`. We can assume any check that raises an exception has failed. I think `can()` should be a 'safe' method that should only raise exceptions when programming errors (like missing policies) are involved.

**Comment by robertpustulka** [comment]
I'm not sure I understood everything correctly but it looks to me like you're trying to implement your app behavior in your policies by throwing exceptions. Policy classes should only define only your authorization rules - what a user can do or can't with a given resource. The behavior (how to handle your authorization) should be placed elsewhere (your application layer or however you call it) and there you should check your rules (call `can`) and react appropriately (pass, throw exception, redirect etc).

**Comment by Zuluru** [comment]
A policy might reject the current user for various reasons. I need to be able to send the user to different places, and display different messages, depending on *why* they were rejected. A simple true/false return value is insufficient for this. Throwing exceptions with these details attached is how I thought to handle it, and Mark agreed.

**Comment by robertpustulka** [comment]
Maybe you should implement your own component instead of altering the plugin behavior to satisfy your use case?

**Comment by Zuluru** [comment]
If this is something that I'm the only one that's ever going to run into, then sure. But it seems like the sort of thing that many people would benefit from, and Mark seemed to agree. My suggested changes don't break any existing behaviour, they extend it, so anyone that doesn't need this is unaffected.

**Comment by robertpustulka** [comment]
Another option would be to create a DTO wrapping your resource and check permissions on it instead of the resource. Then your policy could set failure reason or some additional context so you could check the reason value afterwards and take an action accordingly.

I just don’t like that the policies would be expected to throw exceptions and that the layer above would silence them. It seems like a bad solution.

**Comment by Zuluru** [comment]
Certainly another possibility, though it feels less DRY to have to create DTOs everywhere and then throw exceptions from dozens of locations instead of just the policies. Also, `authorize` already throws exceptions for failures, so having the policies throw their own (extending the plugin's ForbiddenException) "feels" like it fits nicely into that paradigm. It just causes problems when using `can` instead of `authorize`.

There's nothing in here that *requires* policies to throw exceptions. It just adds it as an option for those who would benefit from it.

**Comment by robertpustulka** [comment]
`authorize` in component throw an exception, yes. But `can` doesn’t because it is used for checking the permissions. I just worry that this would encourage people to misuse the plugin.

I agree that the failure reason would be very helpful, and we might have missed that. Maybe policies should have returned an object with additional context instead of just a boolean? It is something to consider for 2.0

**Comment by markstory** [comment]
Do return objects require a breaking change? I think we can accommodate booleans and a new return object to give more descriptive failures. It would be an opt-in behavior that would allow the component to raise more descriptive errors covering this use case and potentially others.

A failure object could provide;

* statusCode
* reason

**Comment by Zuluru** [comment]
So, when the policy returns an object, `authorize` would throw a ForbiddenException with that object attached and `can` would return false? I expect that could work. I'll look at it more today. I'd like to see flash key (info, warning, error) included as well, and also redirect URL.

Would we provide a default DTO for this with whatever fields are agreed upon, and people can extend or replace it if they have other needs? A generic DTO that allows any fields the user wants? Just take arrays?

**Comment by robertpustulka** [comment]
> I'd like to see flash key (info, warning, error) included as well, and also redirect URL.

This doesn't look like a policy concern. Policy may return true/false and a reason it does so. Your component or whatever should make a decision how to handle this and redirect, set flash message etc. 

We have developed this plugin (and Authentication) in order to decouple mixed app layers in AuthComponent. I wouldn't like to reintroduce that.

@markstory Should the object bubble up from the policy, through the service and into the component being returned with AuthorizationComponent? This shouldn't break people's code if they return bools from their policies and expect those bools in their controllers.

**Comment by Zuluru** [comment]
The reason and the redirect URL are connected. If they can't do something because they need to sign a waiver first, they should redirect to the waiver page, otherwise, to the home page. And the waiver should be an informational message where others would be errors. Having my multiple calling locations all make those determinations based on a single return value isn't DRY.

**Comment by robertpustulka** [comment]
@Zuluru as I said - putting redirects in policies is mixing layers and I wouldn't do that. We can provide a simple interface for result classes with `statusCode` and a `reason` only as Mark suggested. You could extend this interface and provide some additional data like flash message or redirect, but I don't think we should include that in the plugin as in my opinion it's just a bad design to make decision in your application layer on what your communication layer should do.

**Comment by Zuluru** [comment]
I see your point. If the details that get passed to the registered handler function include the resource that was passed into the policy, along with the reason (thinking that, at least in my case, the reason might be a defined constant), then I think that should be sufficient for me to make the determination of where to redirect to, what message to add, and whether it's an info, warning or error message.

Are you saying you'd put together the interface, or is that something you're looking for me to contribute?

**Comment by robertpustulka** [comment]
Looks like this can already be achieved with custom policy results as [1.1.0](https://github.com/cakephp/authorization/releases/tag/1.1.0) has been released.

**Comment by dereuromark** [comment]
But the flash message part on redirect wasn't solved was it?
Refs https://github.com/cakephp/authentication/issues/316

Maybe the flash messages should be a trait or on the request instead of a component.

**Comment by markstory** [comment]
I think we're missing an unauthorized handler that sets a flash message into the session and redirects.
