### ISSUE TITLE
`can` documentation issue?

### ISSUE THREAD

**Issue by waspinator** [cakephp/authorization#81]
should the parameters in `can($this, $action, $resource);` be switched to `can($this,  $resource, $action);` in the documentation?

It seems different in https://github.com/cakephp/authorization/blob/f745fe6fd6c81a0e7ee8d3fc933ef878491c0906/src/Controller/Component/AuthorizationComponent.php#L97

https://book.cakephp.org/authorization/1.1/en/middleware.html#identity-decorator
```
class User extends Entity implements IdentityInterface
{

    /**
     * Authorization\IdentityInterface method
     */
    public function can($action, $resource)
    {
        return $this->authorization->can($this, $action, $resource);
    }
...
```

**Comment by markstory** [comment]
The argument order is different between the user identity interface and authorization component. This was done to allow the component to have `action` be an optional argument that defaults to the current controller action.

**Comment by waspinator** [comment]
but when I use the code as documented I get a `Authorization\Policy\Exception\MissingPolicyException`: `Policy for `string` has not been defined.`. When I switch it to 

```
    /**
     * Authorization\IdentityInterface method
     */
    public function can($action, $resource)
    {
        return $this->authorization->can($this, $resource, $action);
    }
```

it seems to work.

**Comment by markstory** [comment]
Does your user have a reference to the AuthorizationComponent or the AuthorizationService? Generally Identity objects have the [AuthorizationService](https://github.com/cakephp/authorization/blob/f745fe6fd6c81a0e7ee8d3fc933ef878491c0906/src/AuthorizationService.php#L51) which takes `user, action, resource`

**Comment by waspinator** [comment]
Hmm, it looks like I'm using service with the user entity and the component in controllers? How would I check authorization using the service instead of the component? why would I want to use one vs the other?

I'm following the [Quick Start](https://book.cakephp.org/authorization/1.1/en/index.html) guide, but maybe it doesn't expect me to use a custom user entity?

`debug($this->Authorization);die;`
```
object(Authorization\Controller\Component\AuthorizationComponent) {

	'components' => [],
	'implementedEvents' => [
		'Controller.startup' => 'authorizeAction'
	],
	'_config' => [
		'identityAttribute' => 'identity',
		'serviceAttribute' => 'authorization',
		'authorizationEvent' => 'Controller.startup',
		'skipAuthorization' => [
			(int) 0 => 'display'
		],
		'authorizeModel' => [],
		'actionMap' => []
	]

}
```

`debug($this->request->getAttribute('identity'));die;`
```
object(App\Model\Entity\User) {
        ...
	'authorization' => object(Authorization\AuthorizationService) {
		[protected] resolver => object(Authorization\Policy\OrmResolver) {
			[protected] appNamespace => 'App'
			[protected] overrides => []
		}
		[protected] authorizationChecked => false
	},
...
```

`AppController.php`
```
public function initialize()
{
...
    $this->loadComponent('Authorization.Authorization', [
        'skipAuthorization' => [
            'display'
        ]
    ]);
}
```

`UsersController.php`

```
public function view($id)
{
    $this->Crud->on('afterFind', function (Event $event) {
        $entity = $event->getSubject()->entity;
        $user = $this->request->getAttribute('identity');

        ---1---
        // Forbidden
        // Cake\Http\Exception\ForbiddenException
        if (!$user->can('view', $entity)) {
            throw new \Cake\Http\Exception\ForbiddenException;
        }

        ---2---
        // Identity is not authorized to perform `view` on `App\Model\Entity\User`.
        // Authorization\Exception\ForbiddenException
        $this->Authorization->authorize($entity, 'view');

        ---3---
        // Policy for `string` has not been defined.
        // Authorization\Policy\Exception\MissingPolicyException;
        $this->Authorization->authorize('view', $entity);

    });
    
    return $this->Crud->execute();
}
```


`User.php`
```
class User extends Entity implements AuthorizationIdentity, AuthenticationIdentity 
{
...
    public function can($action, $resource)
    {
        return $this->authorization->can($this, $action, $resource);
    }
    
    public function applyScope($action, $resource)
    {
        return $this->authorization->applyScope($this, $action, $resource);
    }
    
    public function setAuthorization(AuthorizationService $service)
    {
        $this->authorization = $service;
        return $this;
    }
}
```

**Comment by markstory** [comment]
Your 3rd example in the controller is incorrect. Your controller is using the Component which takes `resource, action`.
