### ISSUE TITLE
requireScope similar to requireAuthorizationCheck?

### ISSUE THREAD

**Issue by dangerdan** [cakephp/authorization#84]
I'm migrating to the new authorization plugin and I'm really impressed as policies are allowing me to remove all kinds of tenant specific logic. However, a couple of times i've inadvertently stumbled as some of my actions deal with both entities and queries in the same request.

Because i've added an entity authorize() check, nothing is enforcing me to add a scope where needed. Should this be provided as another config option?

We'd somehow have to know whether a scope has been applied to a query already, and then throw an error if the 'requireScope' or similar was true.

Thoughts? Am I missing something here?

**Comment by markstory** [comment]
> We'd somehow have to know whether a scope has been applied to a query already, and then throw an error if the 'requireScope' or similar was true.

What would that look like, how would the framework let you know that scope hadn't been applied?

**Comment by dangerdan** [comment]
An exception similar to what is thrown already via 'requireAuthorizationCheck' would work, configurable as 'requireScopeCheck' or similiar. This would ensure filtering isn't missed for queries that need it, as currently skipping authorization or just checking entity authorization prevents the exception being thrown. This could cause a miss when trying to migrate existing code.

I've had this issue myself as I'm moving tenant code from a custom orm behavior class to use this plugin.

**Comment by markstory** [comment]
Is the desire to have a check that ensures that all queries created during the request have scopes applied or just that any query had a scope applied?

**Comment by dangerdan** [comment]
Good question! Probably all queries? Happy for others to input?

**Comment by dereuromark** [comment]
@dangerdan You can make a PR here. But this should probably be defaulting to false :)

**Comment by othercorey** [comment]
Closing unless user wants to submit a PR. We don't plan to require every request to scope a query.
