### ISSUE TITLE
Policy for `Cake\Http\ServerRequest` has not been defined.

### ISSUE THREAD

**Issue by phpraven** [cakephp/authorization#88]
Hello,
Im trying to add authorization to my application but Im getting this error message: Policy for `Cake\Http\ServerRequest` has not been defined.
![1](https://user-images.githubusercontent.com/12783504/57967837-b82a1680-7963-11e9-8945-30102e393b6e.png)
![2](https://user-images.githubusercontent.com/12783504/57967838-b82a1680-7963-11e9-8b4f-5fc99c372a3b.png)
![3](https://user-images.githubusercontent.com/12783504/57967839-b82a1680-7963-11e9-8081-2bc3f37d7d99.png)

Thanks for help

**Comment by markstory** [comment]
You make a `mapResolver` but never put it into the AuthorizationService, so the service has no idea that the mapResolver ever existed. You should do the following in your `getAuthorizationService()` method.

```php
$orm = new OrmResolver();
$map = new MapResolver();
$map->map(ServerRequest::class, RequestPolicy::class);

return new AuthorizationService(new ResolverCollection($orm, $map));
```

The ``ResolverCollection` lets you aggregate multiple resolvers together which is what I think you're trying to do.

**Comment by aokazu** [comment]
The argument to ResolverCollection did not work unless it was an array.

**Before**
`return new AuthorizationService (new ResolverCollection ($ orm, $ map));`

**Afte**
`return new AuthorizationService (new ResolverCollection ([$ orm, $ map]));`

**Comment by aokazu** [comment]
The argument to ResolverCollection did not work unless it was an array.

**Before**
`return new AuthorizationService (new ResolverCollection ($orm, $map));`

**After**
`return new AuthorizationService (new ResolverCollection ([$orm, $map]));`
