### ISSUE TITLE
Order of properties in user->applyScope(); vs Authorization->applyScope();

### ISSUE THREAD

**Issue by dangerdan** [cakephp/authorization#89]
In the AuthorizationComponent we have:
    public function applyScope($resource, $action = null) 

Verses this in the IdentityDecorator:
    public function applyScope($action, $resource)

Is there a reason for the mismatch?

**Comment by markstory** [comment]
> Is there a reason for the mismatch?

Yes. In the `AuthorizationComponent` the `action` defaults to the current controller action.
