### ISSUE TITLE
Concrete use cases

### ISSUE THREAD

**Issue by irongomme** [cakephp/authorization#91]
Is there any way to see a real implementation of this plugin ?

I understand the idea for using it, but I'd like to see some exemple / use cases to know how to use it correctly.

Thxs

**Comment by markstory** [comment]
Not yet, but that is something that has been on my todo list for a while. It would be good to update the CMS tutorial in the cookbook to use the authorization and authentication plugins.

**Comment by dereuromark** [comment]
@irongomme If you are interested you can also take one of the existing demo apps, the sandbox or the [cakefest app](http://cakefest.dereuromark.de/) and apply it to those.
Once deployed everyone can then see the real demo.
