### ISSUE TITLE
conventions for table and query policy 

### ISSUE THREAD

**Issue by waspinator** [cakephp/authorization#96]
I'm not sure if the conventions for table objects and query policies are missing from the docs or if I'm not reading things right. And just checking,`bake` only generates entity policy files at the moment?

entity: `cake bake policy User`
table: `cake bake policy --type=table Users` creates something fairly bare-bones 

https://book.cakephp.org/authorization/1.1/en/policies.html#creating-policies

> table objects and queries can have policies resolved. These objects use the following conventions:

**Comment by markstory** [comment]
Looks like a block of text was lost in the conversion from markdown to RST. The table policies that bake generates are bare-bones because there aren't many conventions that bake can easily apply. However, if you have an idea on how to improve it we could explore that.

**Comment by dereuromark** [comment]
Looks like a commit was done
