### ISSUE TITLE
encapsulate decision logic

### ISSUE THREAD

**Issue by erfunath** [cakephp/authorization#97]
I've dug through the documentation and spent hours trying to find a way to do this. I have nested associations that run several layers deep, and cannot seem to find a place to put decision logic. E.g., I have Users that belong to many Courses through CourseMemberships, and the CourseMemberships have fields that need to be checked (e.g., valid dates) before the policy method can return true or false.

I cannot find a place to encapsulate this logic so that I don't have to copy and paste it between policies and methods for my two dozen models. For example, if this were Controller level rather than policy, I would just dump it all into a component and call that when it's needed. Is there somewhere to put all this and I'm just missing it?

**Comment by markstory** [comment]
> I cannot find a place to encapsulate this logic so that I don't have to copy and paste it between policies and methods for my two dozen models. For example, if this were Controller level rather than policy, I would just dump it all into a component and call that when it's needed. Is there somewhere to put all this and I'm just missing it?

Have you considered making a base class or trait for your application policies and putting the shared logic there?

**Comment by erfunath** [comment]
I did end up creating a base class. I just wanted to be sure I wasn't breaking a convention somewhere in doing so. Cheers!
